import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";
import { requireAuthenticatedRequest } from "../_shared/auth.ts";
import { readJsonBody } from "../_shared/body.ts";
import { buildCorsHeaders } from "../_shared/cors.ts";
import { getDecryptedSecret } from "../_shared/secrets.ts";
interface FileManifestEntry {
  path: string;
  content: string | null;
  operation: "upsert" | "delete";
  content_hash?: string;
}

interface AgentPatch {
  agent_name: string;
  agent_id: string;
  content: string;
  scoped_paths: string[];
  commit_message: string;
  conductor_approved?: boolean;
  file_manifest?: FileManifestEntry[];
}

interface ManifestExecutionResult {
  written_files: string[];
  deleted_files: string[];
  skipped_files: Array<{ path: string; reason: string }>;
  out_of_scope: Array<{ path: string; content: string | null; operation: "upsert" | "delete" }>;
  errors: string[];
}

// UTF-8 safe base64 encoder. The classic btoa(unescape(encodeURIComponent(...)))
// hack is deprecated and breaks on emoji/CJK. This handles all of Unicode and
// large files via chunked spread.
function utf8ToBase64(str: string): string {
  const bytes = new TextEncoder().encode(str);
  let binary = "";
  const chunkSize = 0x8000;
  for (let i = 0; i < bytes.length; i += chunkSize) {
    binary += String.fromCharCode(...bytes.subarray(i, i + chunkSize));
  }
  return btoa(binary);
}

// Reject obvious model laziness. Catches "// ... existing code ...",
// "// rest of file unchanged", "/* previous imports */", etc.
// This is the first line of defense against an agent overwriting a real
// file with a stub. Tuned for false-negative tolerance, not precision.
const TRUNCATION_PATTERNS = [
  /\/\/\s*\.{2,}\s*(existing|rest|previous|unchanged|other|same|original|prior|above|below|remaining|implementation)/i,
  /\/\*\s*\.{2,}\s*(existing|rest|previous|unchanged|other|same|original|prior|above|below|remaining|implementation)/i,
  /#\s*\.{2,}\s*(existing|rest|previous|unchanged|other|same|original|prior|above|below|remaining|implementation)/i,
  /<!--\s*\.{2,}\s*(existing|rest|previous|unchanged|other|same|original|prior|above|below|remaining|implementation)/i,
  /\/\/\s*(keep|preserve)\s+(existing|original|previous)/i,
];

function looksTruncated(content: string): boolean {
  return TRUNCATION_PATTERNS.some(p => p.test(content));
}

function validateManifestEntry(entry: FileManifestEntry): { ok: true } | { ok: false; reason: string } {
  if (!entry.path || typeof entry.path !== "string") {
    return { ok: false, reason: "missing path" };
  }
  if (entry.path.startsWith("/") || entry.path.includes("..")) {
    return { ok: false, reason: "invalid path (absolute or traversal)" };
  }
  if (entry.path.includes("\\") || entry.path.trim() !== entry.path || entry.path.length > 240) {
    return { ok: false, reason: "invalid path formatting" };
  }
  // Sprint A · B7 — ARCHITECT.md is generated via the architect edge function
  // and stored in sessions.architect_md. It must never be written from a
  // manifest, regardless of casing or directory.
  const baseName = entry.path.split("/").pop() ?? "";
  if (baseName.toLowerCase() === "architect.md") {
    return { ok: false, reason: "ARCHITECT.md is generated by the architect edge function and cannot be written via manifest" };
  }
  if (entry.operation === "delete") {
    if (entry.content !== null) {
      return { ok: false, reason: "delete entry has non-null content" };
    }
    return { ok: true };
  }
  if (entry.operation === "upsert") {
    if (typeof entry.content !== "string") {
      return { ok: false, reason: "upsert entry has null/non-string content" };
    }
    if (entry.content.length === 0) {
      return { ok: false, reason: "upsert entry has empty content" };
    }
    if (entry.content.length > 750_000) {
      return { ok: false, reason: "file content exceeds 750KB safety limit" };
    }
    if (looksTruncated(entry.content)) {
      return { ok: false, reason: "content contains truncation placeholder (// ... existing code etc)" };
    }
    return { ok: true };
  }
  return { ok: false, reason: `unknown operation "${entry.operation}"` };
}

interface ExecuteRequest {
  mode: "per_agent" | "synthesized";
  repo_connection_id: string;
  execution_run_id: string;
  approval_request_id?: string | null;
  session_id?: string | null;
  patches: AgentPatch[];
  synthesis_content?: string;
  commit_message?: string;
  conductor_approved?: boolean;
}

const GITHUB_EXECUTE_MAX_BODY_BYTES = 4_194_304;

interface PathCollision {
  path: string;
  agents: string[];
}

// Sprint A · B4 — collision detection. If two agents claim the same file path,
// we block ONLY the colliding entries; non-colliding files in the same patches
// continue. Result includes the collisions array so the UI can surface them.
function detectCollisions(patches: AgentPatch[]): {
  collisions: PathCollision[];
  collidingPaths: Set<string>;
} {
  const pathMap = new Map<string, Set<string>>();
  for (const patch of patches) {
    if (!patch.file_manifest) continue;
    for (const entry of patch.file_manifest) {
      if (!entry?.path) continue;
      const set = pathMap.get(entry.path) ?? new Set<string>();
      set.add(patch.agent_name);
      pathMap.set(entry.path, set);
    }
  }
  const collisions: PathCollision[] = [];
  const collidingPaths = new Set<string>();
  for (const [path, agents] of pathMap) {
    if (agents.size > 1) {
      collisions.push({ path, agents: [...agents].sort() });
      collidingPaths.add(path);
    }
  }
  return { collisions, collidingPaths };
}

function scopePathsEqual(a: string[], b: string[]): boolean {
  if (a.length !== b.length) return false;
  const sa = [...a].sort();
  const sb = [...b].sort();
  return sa.every((v, i) => v === sb[i]);
}

/**
 * Check if a file path matches any of the scoped path globs.
 * Supports simple glob patterns: * matches within a segment, ** matches across segments.
 */
function pathMatchesScope(filePath: string, scopedPaths: string[]): boolean {
  if (scopedPaths.length === 0) return false;
  for (const pattern of scopedPaths) {
    if (globMatch(filePath, pattern)) return true;
  }
  return false;
}

function globMatch(path: string, pattern: string): boolean {
  // Normalize separators
  const p = path.replace(/\\/g, "/");
  const g = pattern.replace(/\\/g, "/");

  // Convert glob to regex
  let regex = "^";
  let i = 0;
  while (i < g.length) {
    if (g[i] === "*" && g[i + 1] === "*") {
      // ** matches any number of path segments
      regex += ".*";
      i += 2;
      if (g[i] === "/") i++; // skip trailing slash after **
    } else if (g[i] === "*") {
      // * matches anything except /
      regex += "[^/]*";
      i++;
    } else if (g[i] === "?") {
      regex += "[^/]";
      i++;
    } else if (".+^${}()|[]\\".includes(g[i])) {
      regex += "\\" + g[i];
      i++;
    } else {
      regex += g[i];
      i++;
    }
  }
  regex += "$";

  return new RegExp(regex).test(p);
}

interface ScopeCheckResult {
  allowed: boolean;
  reason: string;
}

function checkAgentScope(patch: AgentPatch, globalApproval: boolean): ScopeCheckResult {
  const hasPaths = patch.scoped_paths && patch.scoped_paths.length > 0;
  const approved = patch.conductor_approved || globalApproval;

  if (!hasPaths && !approved) {
    return {
      allowed: false,
      reason: `${patch.agent_name} has no scoped paths declared and no conductor approval. Write blocked.`,
    };
  }

  return { allowed: true, reason: "" };
}

function hasWriteManifest(patch: AgentPatch): boolean {
  return Array.isArray(patch.file_manifest) && patch.file_manifest.length > 0;
}

async function ghApi(path: string, token: string, options: RequestInit = {}) {
  const res = await fetch(`https://api.github.com${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      "User-Agent": "Maestro",
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json",
      ...((options.headers as Record<string, string>) || {}),
    },
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data.message || `GitHub API ${res.status}`);
  return data;
}

async function createBranch(owner: string, repo: string, branchName: string, baseSha: string, token: string) {
  return ghApi(`/repos/${owner}/${repo}/git/refs`, token, {
    method: "POST",
    body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha: baseSha }),
  });
}

function isEmptyRepoError(err: unknown): boolean {
  const message = err instanceof Error ? err.message : String(err);
  return /repository is empty/i.test(message);
}

async function ensureDefaultBranchSha(
  owner: string,
  repo: string,
  defaultBranch: string,
  token: string,
): Promise<{ sha: string; initialized: boolean }> {
  try {
    const ref = await ghApi(`/repos/${owner}/${repo}/git/ref/heads/${defaultBranch}`, token) as { object?: { sha?: string } };
    const sha = ref?.object?.sha;
    if (!sha) throw new Error(`Default branch ${defaultBranch} is missing a commit SHA.`);
    return { sha, initialized: false };
  } catch (err) {
    if (!isEmptyRepoError(err)) throw err;

    const tree = await ghApi(`/repos/${owner}/${repo}/git/trees`, token, {
      method: "POST",
      body: JSON.stringify({ tree: [] }),
    }) as { sha?: string };

    const rootCommit = await ghApi(`/repos/${owner}/${repo}/git/commits`, token, {
      method: "POST",
      body: JSON.stringify({
        message: "[Maestro] Initialize repository",
        tree: tree.sha,
        parents: [],
      }),
    }) as { sha?: string };

    if (!tree?.sha || !rootCommit?.sha) {
      throw new Error("Failed to initialize the default branch for an empty repository.");
    }

    try {
      await ghApi(`/repos/${owner}/${repo}/git/refs`, token, {
        method: "POST",
        body: JSON.stringify({ ref: `refs/heads/${defaultBranch}`, sha: rootCommit.sha }),
      });
    } catch (createErr) {
      const message = createErr instanceof Error ? createErr.message : String(createErr);
      if (!/reference already exists/i.test(message)) throw createErr;
    }

    const ref = await ghApi(`/repos/${owner}/${repo}/git/ref/heads/${defaultBranch}`, token) as { object?: { sha?: string } };
    const sha = ref?.object?.sha;
    if (!sha) throw new Error(`Default branch ${defaultBranch} could not be initialized.`);
    return { sha, initialized: true };
  }
}// Sprint A · B5 — automatic backup branch. Snapshots default branch HEAD
// before any write to an existing repo. Once per execution run, never
// skippable, no override flag. Returns the branch name.
async function createBackupBranch(
  owner: string,
  repo: string,
  defaultBranch: string,
  token: string,
): Promise<string> {
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
  const backupBranch = `maestro-backup/${timestamp}`;
  const ref = await ghApi(`/repos/${owner}/${repo}/git/ref/heads/${defaultBranch}`, token);
  await ghApi(`/repos/${owner}/${repo}/git/refs`, token, {
    method: "POST",
    body: JSON.stringify({ ref: `refs/heads/${backupBranch}`, sha: ref.object.sha }),
  });
  return backupBranch;
}

async function getExistingFile(
  owner: string,
  repo: string,
  branch: string,
  path: string,
  token: string,
): Promise<{ sha: string; size: number } | null> {
  try {
    const data = await ghApi(
      `/repos/${owner}/${repo}/contents/${encodeURIComponent(path)}?ref=${branch}`,
      token,
    );
    return { sha: data.sha, size: data.size ?? 0 };
  } catch {
    return null;
  }
}

async function upsertFile(
  owner: string,
  repo: string,
  branch: string,
  path: string,
  content: string,
  message: string,
  token: string,
): Promise<void> {
  const existing = await getExistingFile(owner, repo, branch, path, token);

  // Length sanity guard: if the new file is dramatically smaller than the
  // existing one, the agent probably truncated. Skip with loud reason.
  // Only enforced when existing file is >200 bytes (avoids tripping on stubs).
  if (existing && existing.size > 200) {
    const newBytes = new TextEncoder().encode(content).length;
    if (newBytes < existing.size * 0.3) {
      throw new Error(
        `length sanity check failed: new content (${newBytes}b) is <30% of existing (${existing.size}b) for ${path}`,
      );
    }
  }

  const encoded = utf8ToBase64(content);
  const body: Record<string, unknown> = { message, content: encoded, branch };
  if (existing) body.sha = existing.sha;

  await ghApi(`/repos/${owner}/${repo}/contents/${encodeURIComponent(path)}`, token, {
    method: "PUT",
    body: JSON.stringify(body),
  });
}

async function deleteFile(
  owner: string,
  repo: string,
  branch: string,
  path: string,
  message: string,
  token: string,
): Promise<void> {
  const existing = await getExistingFile(owner, repo, branch, path, token);
  if (!existing) {
    // Already gone; treat as no-op rather than error.
    return;
  }
  await ghApi(`/repos/${owner}/${repo}/contents/${encodeURIComponent(path)}`, token, {
    method: "DELETE",
    body: JSON.stringify({ message, sha: existing.sha, branch }),
  });
}

async function applyManifest(
  manifest: FileManifestEntry[],
  owner: string,
  repo: string,
  branch: string,
  scopedPaths: string[],
  globalApproval: boolean,
  baseMessage: string,
  token: string,
): Promise<ManifestExecutionResult> {
  const out: ManifestExecutionResult = {
    written_files: [],
    deleted_files: [],
    skipped_files: [],
    out_of_scope: [],
    errors: [],
  };

  for (const entry of manifest) {
    const v = validateManifestEntry(entry);
    if (!v.ok) {
      out.skipped_files.push({ path: entry.path || "<unknown>", reason: v.reason });
      continue;
    }

    // Scope enforcement: every entry must match the patch's scoped_paths
    // unless conductor approval is set globally. Skip the entry, do NOT
    // abort the run — partial success beats total failure.
    const inScope = scopedPaths.length > 0 && pathMatchesScope(entry.path, scopedPaths);
    if (!inScope && !globalApproval) {
      // Sprint B · B4 — out-of-scope entries become handoff requests rather
      // than silent skips. Caller persists to handoff_requests.
      out.out_of_scope.push({
        path: entry.path,
        content: entry.content,
        operation: entry.operation,
      });
      out.skipped_files.push({
        path: entry.path,
        reason: "out of scope — handoff requested",
      });
      continue;
    }

    try {
      if (entry.operation === "delete") {
        await deleteFile(owner, repo, branch, entry.path, `${baseMessage} (delete ${entry.path})`, token);
        out.deleted_files.push(entry.path);
      } else {
        await upsertFile(
          owner, repo, branch, entry.path,
          entry.content as string,
          `${baseMessage} (${entry.path})`,
          token,
        );
        out.written_files.push(entry.path);
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      out.errors.push(`${entry.path}: ${msg}`);
      out.skipped_files.push({ path: entry.path, reason: `write failed: ${msg}` });
    }
  }

  return out;
}

async function createPR(owner: string, repo: string, head: string, base: string, title: string, body: string, token: string) {
  return ghApi(`/repos/${owner}/${repo}/pulls`, token, {
    method: "POST",
    body: JSON.stringify({ title, body, head, base }),
  });
}

Deno.serve(async (req: Request) => {
  const corsHeaders = buildCorsHeaders(req);
  if (req.method === "OPTIONS") {
    return new Response(null, { status: 200, headers: corsHeaders });
  }

  try {
    const auth = await requireAuthenticatedRequest(req, corsHeaders, "github-execute");
    if (auth instanceof Response) {
      return auth;
    }

    const { adminClient: supabase, authHeader, userId } = auth;
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;

    const bodyResult = await readJsonBody<ExecuteRequest>(req, corsHeaders, {
      maxBytes: GITHUB_EXECUTE_MAX_BODY_BYTES,
      label: "GitHub execute request body",
    });
    if (bodyResult instanceof Response) {
      return bodyResult;
    }
    const body = bodyResult;
    const { mode, repo_connection_id, execution_run_id, session_id, synthesis_content, commit_message } = body;
    if (mode !== "per_agent" && mode !== "synthesized") {
      return new Response(
        JSON.stringify({
          error: "INVALID_EXECUTION_MODE",
          message: "github-execute requires mode to be either per_agent or synthesized.",
        }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    // Hard guard: patches must be a non-empty array. Frontend can send an
    // empty/undefined patches array if the user fires Build before any
    // responses are selected — every downstream .map/.flatMap would crash.
    const patches: AgentPatch[] = Array.isArray(body.patches) ? body.patches : [];
    if (patches.length === 0) {
      return new Response(
        JSON.stringify({
          error: "NO_PATCHES",
          message: "No patches were submitted. Select at least one agent response before executing.",
        }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    let repoConn: Record<string, unknown> | null = null;
    if (repo_connection_id) {
      const { data } = await supabase
        .from("repo_connections")
        .select("*")
        .eq("id", repo_connection_id)
        .eq("user_id", userId)
        .maybeSingle();
      repoConn = data;
    }

    // Fallback — if the explicit id is missing or stale (frontend state drift,
    // cross-workspace switch, deleted row) look up the active repo connection
    // for the session's workspace. This unblocks builds when the cached id
    // no longer points anywhere valid.
    if (!repoConn && session_id) {
      const { data: sessRow } = await supabase
        .from("sessions")
        .select("workspace_id")
        .eq("id", session_id)
        .eq("user_id", userId)
        .maybeSingle();
      const wsId = (sessRow as { workspace_id?: string } | null)?.workspace_id;
      if (wsId) {
        const { data: activeConn } = await supabase
          .from("repo_connections")
          .select("*")
          .eq("workspace_id", wsId)
          .eq("user_id", userId)
          .eq("is_active", true)
          .order("created_at", { ascending: false })
          .limit(1)
          .maybeSingle();
        repoConn = activeConn;
      }
    }

    if (!repoConn) {
      return new Response(
        JSON.stringify({
          error: "Repo connection not found",
          message: `No repo connection matched id "${repo_connection_id ?? "(none)"}" and no active repo connection exists for this session's workspace. Reconnect or pick a repo in the New App panel.`,
          repo_connection_id: repo_connection_id ?? null,
        }),
        { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    const ghToken = await getDecryptedSecret(supabase, userId, "github");

    if (!ghToken) {
      return new Response(JSON.stringify({ error: "GitHub not connected" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    const owner = repoConn.owner;
    const repo = repoConn.repo;
    const defaultBranch = repoConn.default_branch || "main";

    // P11 — Elevated runs must reference a valid, scope-matching approval_request.
    const { data: runRow } = await supabase
      .from("execution_runs")
      .select("execution_mode")
      .eq("id", execution_run_id)
      .eq("user_id", userId)
      .maybeSingle();

    // Sprint A · B4 — build spec freeze gate. Any non-analyze run requires the
    // session to have completed pre-build and locked its build_spec. Analyze
    // mode bypasses this. Hard gate, no override.
    if (runRow?.execution_mode && runRow.execution_mode !== "analyze") {
      if (!session_id) {
        return new Response(
          JSON.stringify({
            error: "BUILD_SPEC_NOT_LOCKED",
            message: "Execution run is missing session_id. Cannot verify build spec lock.",
          }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
        );
      }
      const { data: sessionRow } = await supabase
        .from("sessions")
        .select("build_spec_locked, current_phase")
        .eq("id", session_id)
        .maybeSingle();

      if (!sessionRow?.build_spec_locked) {
        return new Response(
          JSON.stringify({
            error: "BUILD_SPEC_NOT_LOCKED",
            message: "Complete pre-build phase and lock build spec before executing.",
          }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
        );
      }

      // Sprint B · B5 — build lane assignment gate. Mirrors build_spec_locked.
      // pr_flow + elevated both blocked without lanes. Analyze bypasses (above).
      const { data: laneRows } = await supabase
        .from("build_lanes")
        .select("agent_id, agent_name, lane_paths, role")
        .eq("session_id", session_id);

      const writingPatches = patches.filter(hasWriteManifest);
      const builderLanes = (laneRows ?? []).filter((l) => l.role === "builder");
      if (writingPatches.length > 0 && builderLanes.length === 0) {
        return new Response(
          JSON.stringify({
            error: "LANES_NOT_ASSIGNED",
            message: "Code-writing builder agents must have non-overlapping lane assignments before build can execute",
          }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
        );
      }

      // Only patches that contain actual file writes require a builder lane.
      // Reviewer/read_only/prose-only responses may be included in the run
      // context, but they must not block execution just because they lack
      // build_lanes rows.
      // Match by agent_id first (reliable), then by agent_name (fallback).
      const laneAgentIds = new Set(builderLanes.map((l) => l.agent_id).filter(Boolean));
      const laneAgentNames = new Set(builderLanes.map((l) => l.agent_name));
      const missing = writingPatches
        .map((p) => p.agent_name)
        .filter((n, i) => {
          const patchAgentId = writingPatches[i].agent_id;
          return !laneAgentIds.has(patchAgentId) && !laneAgentNames.has(n);
        });
      if (missing.length > 0) {
        return new Response(
          JSON.stringify({
            error: "LANES_NOT_ASSIGNED",
            message: `Builder agents missing lane assignment: ${missing.join(", ")}`,
          }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
        );
      }

      // No two builder lanes may share a path
      const seen = new Map<string, string>();
      for (const lane of builderLanes) {
        for (const p of (lane.lane_paths as string[] | null) ?? []) {
          if (seen.has(p)) {
            return new Response(
              JSON.stringify({
                error: "LANES_NOT_ASSIGNED",
                message: `Lane path "${p}" is claimed by both ${seen.get(p)} and ${lane.agent_name}`,
              }),
              { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
            );
          }
          seen.set(p, lane.agent_name);
        }
      }
    }

    if (runRow?.execution_mode === "elevated") {
      if (!body.approval_request_id) {
        return new Response(
          JSON.stringify({ error: "Elevated execution requires approval_request_id" }),
          { status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" } },
        );
      }

      const { data: approval } = await supabase
        .from("approval_requests")
        .select("*")
        .eq("id", body.approval_request_id)
        .eq("user_id", userId)
        .maybeSingle();

      if (!approval || approval.status !== "approved") {
        return new Response(
          JSON.stringify({ error: "Approval request not found or not approved" }),
          { status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" } },
        );
      }

      if (approval.expires_at && new Date(approval.expires_at).getTime() < Date.now()) {
        return new Response(
          JSON.stringify({ error: "Approval has expired" }),
          { status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" } },
        );
      }

      if (approval.repo_connection_id !== repo_connection_id) {
        return new Response(
          JSON.stringify({ error: "Approval scope mismatch: repo_connection_id" }),
          { status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" } },
        );
      }

      if ((approval.branch_name ?? "") !== defaultBranch) {
        return new Response(
          JSON.stringify({ error: "Approval scope mismatch: branch_name" }),
          { status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" } },
        );
      }

      // Derive effective scope paths from this request: union across patches,
      // or [] if any patch is unscoped or conductor_approved is set globally.
      const anyUnscoped = (body.conductor_approved ?? false)
        || patches.some(p => !p.scoped_paths || p.scoped_paths.length === 0);
      const effectiveScope = anyUnscoped
        ? []
        : Array.from(new Set(patches.flatMap(p => p.scoped_paths))).sort();

      if (!scopePathsEqual(approval.scope_paths ?? [], effectiveScope)) {
        return new Response(
          JSON.stringify({ error: "Approval scope mismatch: scope_paths" }),
          { status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" } },
        );
      }
    }

    await supabase
      .from("execution_runs")
      .update({ status: "running" })
      .eq("id", execution_run_id);

    const { sha: baseSha, initialized: initializedDefaultBranch } = await ensureDefaultBranchSha(owner, repo, defaultBranch, ghToken);

    const globalApproval = body.conductor_approved ?? false;

    // Aggregated structured result for the whole run.
    const aggregate: ManifestExecutionResult & {
      branches: Array<{ agent?: string; branch: string; pr_url: string }>;
      prs: string[];
      blocked: Array<{ agent: string; reason: string }>;
      collisions: PathCollision[];
      backup_branch: string | null;
      handoffs_requested: Array<{ from_agent: string; to_lane: string; path: string; reason: "out_of_scope" }>;
    } = {
      written_files: [],
      deleted_files: [],
      skipped_files: [],
      out_of_scope: [],
      errors: [],
      branches: [],
      prs: [],
      blocked: [],
      collisions: [],
      backup_branch: null,
      handoffs_requested: [],
    };

    // Sprint A · B5 — automatic backup branch. Once per run, before any write,
    // for any existing repo. Skipped only when sessions.project_type='new'.
    // Never skippable by flag.
    let projectType: string | null = null;
    if (session_id) {
      const { data: ptRow } = await supabase
        .from("sessions")
        .select("project_type")
        .eq("id", session_id)
        .maybeSingle();
      projectType = (ptRow?.project_type as string | null) ?? null;
    }
    if (projectType !== "new" && !initializedDefaultBranch) {
      try {
        aggregate.backup_branch = await createBackupBranch(owner, repo, defaultBranch, ghToken);
        await supabase.from("audit_events").insert({
          user_id: userId,
          session_id: session_id ?? null,
          event_type: "backup_branch_created",
          actor: "github-execute",
          provider: "github",
          model: aggregate.backup_branch,
          execution_mode: runRow?.execution_mode ?? "",
          requires_approval: false,
          succeeded: true,
        });
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        // Backup is never skippable. If we can't snapshot, refuse to write.
        await supabase
          .from("execution_runs")
          .update({ status: "failed", result: { error: "BACKUP_FAILED", message: msg } })
          .eq("id", execution_run_id);
        return new Response(
          JSON.stringify({
            error: "BACKUP_FAILED",
            message: `Could not create backup branch: ${msg}`,
          }),
          { status: 502, headers: { ...corsHeaders, "Content-Type": "application/json" } },
        );
      }
    }

    // Sprint A · B4 — collision detection. Compute once for the whole run.
    // Colliding paths are filtered out of each manifest before applyManifest.
    // Non-colliding files in the same patches still execute normally.
    const { collisions, collidingPaths } = detectCollisions(patches);
    aggregate.collisions = collisions;
    for (const c of collisions) {
      for (const agent of c.agents) {
        aggregate.skipped_files.push({
          path: c.path,
          reason: `collision: also claimed by ${c.agents.filter(a => a !== agent).join(", ")}`,
        });
      }
    }
    if (collisions.length > 0) {
      await supabase.from("audit_events").insert({
        user_id: userId,
        session_id: session_id ?? null,
        event_type: "collision_detected",
        actor: "github-execute",
        provider: "github",
        model: "",
        execution_mode: runRow?.execution_mode ?? "",
        requires_approval: false,
        succeeded: false,
      });
    }

    // Filter colliding entries out of each patch's manifest before execution.
    const filterManifest = (entries: FileManifestEntry[] | undefined) =>
      (entries ?? []).filter(e => !collidingPaths.has(e.path));

    if (mode === "per_agent") {
      for (const patch of patches) {
        const scopeCheck = checkAgentScope(patch, globalApproval);
        if (!scopeCheck.allowed) {
          aggregate.blocked.push({ agent: patch.agent_name, reason: scopeCheck.reason });
          continue;
        }

        // Loud failure: no fallback to maestro-patches/. If the agent didn't
        // emit a manifest, the run for this patch fails visibly.
        if (!patch.file_manifest || patch.file_manifest.length === 0) {
          aggregate.errors.push(
            `${patch.agent_name}: no file_manifest in response. Re-broadcast in Build mode.`,
          );
          aggregate.blocked.push({
            agent: patch.agent_name,
            reason: "no file_manifest emitted (agent must return real file changes, not prose)",
          });
          continue;
        }

        const filteredManifest = filterManifest(patch.file_manifest);
        if (filteredManifest.length === 0) {
          aggregate.blocked.push({
            agent: patch.agent_name,
            reason: "all manifest entries removed by collision detection",
          });
          continue;
        }

        const slug = patch.agent_name.toLowerCase().replace(/[^a-z0-9]+/g, "-");
        const branchName = `maestro/${slug}/run-${execution_run_id.slice(0, 8)}`;

        try {
          await createBranch(owner, repo, branchName, baseSha, ghToken);
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          aggregate.errors.push(`${patch.agent_name}: branch create failed: ${msg}`);
          continue;
        }

        const baseMsg = patch.commit_message || `[Maestro] ${patch.agent_name} contribution`;
        const manifestResult = await applyManifest(
          filteredManifest,
          owner, repo, branchName,
          patch.scoped_paths ?? [],
          globalApproval || (patch.conductor_approved ?? false),
          baseMsg,
          ghToken,
        );

        aggregate.written_files.push(...manifestResult.written_files);
        aggregate.deleted_files.push(...manifestResult.deleted_files);
        aggregate.skipped_files.push(...manifestResult.skipped_files);
        aggregate.errors.push(...manifestResult.errors);

        // Sprint B · B4 — out-of-scope entries → handoff_requests
        if (manifestResult.out_of_scope.length > 0 && session_id) {
          const handoffRows = manifestResult.out_of_scope.map((e) => ({
            session_id,
            from_agent_id: patch.agent_id || null,
            from_agent_name: patch.agent_name,
            to_lane: e.path,
            request_type: "other" as const,
            description: `Agent ${patch.agent_name} attempted to write ${e.path} outside its declared scope`,
            payload: { path: e.path, content: e.content, operation: e.operation },
          }));
          await supabase.from("handoff_requests").insert(handoffRows);
          for (const e of manifestResult.out_of_scope) {
            aggregate.handoffs_requested.push({
              from_agent: patch.agent_name,
              to_lane: e.path,
              path: e.path,
              reason: "out_of_scope",
            });
          }
        }

        // Only open a PR if at least one file actually changed on this branch.
        const wrote = manifestResult.written_files.length + manifestResult.deleted_files.length;
        if (wrote === 0) {
          aggregate.blocked.push({
            agent: patch.agent_name,
            reason: "manifest produced zero writes (all entries skipped)",
          });
          continue;
        }

        const prBodyLines = [
          `## ${patch.agent_name}`,
          "",
          patch.content,
          "",
          "### Files changed",
          ...manifestResult.written_files.map(f => `- \`${f}\` (upsert)`),
          ...manifestResult.deleted_files.map(f => `- \`${f}\` (delete)`),
        ];
        if (manifestResult.skipped_files.length > 0) {
          prBodyLines.push("", "### Skipped");
          for (const s of manifestResult.skipped_files) {
            prBodyLines.push(`- \`${s.path}\` — ${s.reason}`);
          }
        }
        prBodyLines.push("", "---", "*Generated by Maestro orchestration*");

        const pr = await createPR(
          owner, repo, branchName, defaultBranch,
          `[Maestro] ${patch.agent_name}: ${patch.commit_message || "Agent contribution"}`,
          prBodyLines.join("\n"),
          ghToken,
        );

        aggregate.branches.push({ agent: patch.agent_name, branch: branchName, pr_url: pr.html_url });
        aggregate.prs.push(pr.html_url);
      }

    } else {
      // Synthesized mode: union of all patch manifests on a single branch.
      for (const patch of patches) {
        const scopeCheck = checkAgentScope(patch, globalApproval);
        if (!scopeCheck.allowed) {
          aggregate.blocked.push({ agent: patch.agent_name, reason: scopeCheck.reason });
        }
      }

      const allManifests = patches.flatMap(p => filterManifest(p.file_manifest).map(e => ({
        entry: e,
        scoped_paths: p.scoped_paths ?? [],
        conductor_approved: p.conductor_approved ?? false,
        agent_name: p.agent_name,
        agent_id: p.agent_id,
      })));

      if (allManifests.length === 0) {
        aggregate.errors.push("synthesized run: no file_manifest entries across any patch");
      } else if (aggregate.blocked.length === 0 || globalApproval) {
        const branchName = `maestro/synthesis/run-${execution_run_id.slice(0, 8)}`;
        try {
          await createBranch(owner, repo, branchName, baseSha, ghToken);

          // Apply each manifest entry under its originating patch's scope.
          // Last write wins on path collisions (synthesis-time conflict).
          const baseMsg = commit_message || "[Maestro] Synthesized patch";
          for (const { entry, scoped_paths, conductor_approved, agent_name, agent_id } of allManifests) {
            const single = await applyManifest(
              [entry], owner, repo, branchName, scoped_paths,
              globalApproval || conductor_approved, baseMsg, ghToken,
            );
            aggregate.written_files.push(...single.written_files);
            aggregate.deleted_files.push(...single.deleted_files);
            aggregate.skipped_files.push(...single.skipped_files);
            aggregate.errors.push(...single.errors);

            if (single.out_of_scope.length > 0 && session_id) {
              const handoffRows = single.out_of_scope.map((e) => ({
                session_id,
                from_agent_id: agent_id || null,
                from_agent_name: agent_name,
                to_lane: e.path,
                request_type: "other" as const,
                description: `Agent ${agent_name} attempted to write ${e.path} outside its declared scope`,
                payload: { path: e.path, content: e.content, operation: e.operation },
              }));
              await supabase.from("handoff_requests").insert(handoffRows);
              for (const e of single.out_of_scope) {
                aggregate.handoffs_requested.push({
                  from_agent: agent_name,
                  to_lane: e.path,
                  path: e.path,
                  reason: "out_of_scope",
                });
              }
            }
          }

          const wrote = aggregate.written_files.length + aggregate.deleted_files.length;
          if (wrote > 0) {
            const prBody = [
              "## Council Synthesis",
              "",
              synthesis_content || "",
              "",
              "### Files changed",
              ...aggregate.written_files.map(f => `- \`${f}\` (upsert)`),
              ...aggregate.deleted_files.map(f => `- \`${f}\` (delete)`),
              "",
              "---",
              "*Generated by Maestro orchestration*",
            ].join("\n");

            const pr = await createPR(
              owner, repo, branchName, defaultBranch,
              commit_message || "[Maestro] Synthesized council output",
              prBody, ghToken,
            );
            aggregate.branches.push({ branch: branchName, pr_url: pr.html_url });
            aggregate.prs.push(pr.html_url);
          }
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          aggregate.errors.push(`synthesis branch failed: ${msg}`);
        }
      }
    }

    const totalWrote = aggregate.written_files.length + aggregate.deleted_files.length;
    const status: "success" | "partial" | "failed" =
      totalWrote === 0
        ? "failed"
        : (aggregate.skipped_files.length > 0 || aggregate.errors.length > 0 || aggregate.blocked.length > 0)
          ? "partial"
          : "success";

    const result: Record<string, unknown> = {
      status,
      written_files: aggregate.written_files,
      deleted_files: aggregate.deleted_files,
      skipped_files: aggregate.skipped_files,
      errors: aggregate.errors,
      branches: aggregate.branches,
      prs: aggregate.prs,
      blocked: aggregate.blocked,
      collisions: aggregate.collisions,
      backup_branch: aggregate.backup_branch,
      handoffs_requested: aggregate.handoffs_requested,
    };

    // Sprint B · B7 — auto-generate build report, advance phase, fire bouncer
    let buildReportId: string | null = null;
    if (session_id && totalWrote > 0 && runRow?.execution_mode !== "analyze") {
      const { data: reportRow } = await supabase
        .from("build_reports")
        .insert({
          session_id,
          files_written: aggregate.written_files,
          files_skipped: aggregate.skipped_files,
          collisions: aggregate.collisions,
          handoffs_pending: aggregate.handoffs_requested,
          pr_links: aggregate.prs,
          backup_branch: aggregate.backup_branch,
        })
        .select("id")
        .single();
      buildReportId = (reportRow?.id as string | undefined) ?? null;

      await supabase
        .from("sessions")
        .update({ current_phase: "bouncer" })
        .eq("id", session_id);

      // Fire-and-forget bouncer call. Frontend refetches bouncer_events
      // separately after build completes — do not block the response.
      const bouncerUrl = `${supabaseUrl}/functions/v1/bouncer`;
      fetch(bouncerUrl, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": authHeader,
        },
        body: JSON.stringify({
          session_id,
          trigger: "end_of_build",
          files: aggregate.written_files,
        }),
      }).catch(() => { /* fire-and-forget */ });

      result.build_report_id = buildReportId;
    }

    await supabase
      .from("execution_runs")
      .update({
        status: status === "failed" ? "failed" : "complete",
        result,
        branch_name: aggregate.branches.map(b => b.branch).join(", "),
        pr_url: aggregate.branches.map(b => b.pr_url).join(", "),
      })
      .eq("id", execution_run_id);

    return new Response(JSON.stringify({ success: status !== "failed", result }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });

  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";

    try {
      const body = await req.clone().json().catch(() => ({})) as Record<string, string>;
      if (body.execution_run_id) {
        const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
        const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
        const supabase = createClient(supabaseUrl, supabaseKey);
        await supabase
          .from("execution_runs")
          .update({ status: "failed", result: { error: message } })
          .eq("id", body.execution_run_id);
      }
    } catch { /* best effort */ }

    return new Response(JSON.stringify({ error: message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});













