import { useEffect, useCallback } from 'react';
import { useMaestro } from '../../context/MaestroContext';
import { useOrchestration } from '../../hooks/useOrchestration';
import { supabase } from '../../lib/supabase';
import { X, ArrowRight, RotateCcw, Pencil, Download } from 'lucide-react';

/**
 * ConciergePanel — centered overlay showing the concierge's synthesis decision.
 *
 * Wired to state.conciergeDecision (set by triggerConcierge after synthesis).
 * Auto-shown via SET_CONCIERGE_DECISION reducer which sets conciergeVisible.
 *
 * Actions:
 *   Proceed  → close panel (phase transition placeholder for future wiring)
 *   Round 2  → re-broadcast the latest round's prompt to get fresh responses
 *   Override → close panel, return to manual mode
 */
export default function ConciergePanel() {
  const { state, dispatch } = useMaestro();
  const { broadcast } = useOrchestration();
  const decision = state.conciergeDecision;

  const handleClose = useCallback(() => {
    dispatch({ type: 'SET_CONCIERGE_VISIBLE', payload: false });
  }, [dispatch]);

  const handleProceed = useCallback(async () => {
    handleClose();
    // Advance session phase to 'design'
    if (state.activeSession) {
      await supabase
        .from('sessions')
        .update({ current_phase: 'design' } as never)
        .eq('id', state.activeSession.id);
      dispatch({
        type: 'SET_ACTIVE_SESSION',
        payload: { ...state.activeSession, current_phase: 'design' },
      });
    }
    dispatch({ type: 'SHOW_TOAST', payload: 'Moving to Design phase' });
  }, [handleClose, state.activeSession, dispatch]);

  const handleRound2 = useCallback(() => {
    handleClose();
    const latestRound = state.rounds.length > 0
      ? state.rounds[state.rounds.length - 1]
      : null;
    if (latestRound) {
      const activeAgentIds = state.agents.filter(a => a.is_active).map(a => a.id);
      broadcast(latestRound.prompt, activeAgentIds);
    }
  }, [handleClose, state.rounds, state.agents, broadcast]);

  const handleOverride = useCallback(() => {
    dispatch({ type: 'SET_CONCIERGE_DECISION', payload: null });
    handleClose();
  }, [dispatch, handleClose]);

  const handleDownload = useCallback(() => {
    if (!decision) return;
    const roundNum = state.rounds.length > 0
      ? state.rounds[state.rounds.length - 1].round_number
      : 1;
    const sessionName = state.activeSession?.title ?? 'session';
    const md = [
      `# Concierge Report — ${sessionName} Round ${roundNum}`,
      '',
      '## Where the Council Agrees',
      decision.alignment_summary || '_No alignment summary._',
      '',
      '## Points of Tension',
      ...(decision.tension_points.length > 0
        ? decision.tension_points.map(p => `- ${p}`)
        : ['_No tension points identified._']),
      '',
      '## Recommended Direction',
      decision.recommended_direction || '_No recommendation._',
      '',
      `---`,
      `_Generated by Maestro Concierge${decision.model_used ? ` via ${decision.model_used}` : ''}_`,
    ].join('\n');

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `concierge-report-r${roundNum}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }, [decision, state.rounds, state.activeSession]);

  // Dismiss on Escape
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') handleClose();
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [handleClose]);

  if (!decision) {
    return (
      <div
        className="fixed inset-0 z-50 flex items-center justify-center"
        style={{ background: 'rgba(8,8,6,0.75)', backdropFilter: 'blur(8px)' }}
        onClick={handleClose}
      >
        <div
          onClick={e => e.stopPropagation()}
          style={{
            width: '100%',
            maxWidth: '420px',
            margin: '0 24px',
            padding: '40px 32px',
            borderRadius: '24px',
            border: '1px solid rgba(201,168,76,0.12)',
            background: 'linear-gradient(180deg, rgba(18,17,14,0.98), rgba(12,11,9,0.98))',
            boxShadow: '0 0 80px rgba(201,168,76,0.06), 0 24px 48px rgba(0,0,0,0.4)',
            textAlign: 'center' as const,
          }}
        >
          <div
            style={{
              width: '10px', height: '10px', borderRadius: '50%',
              background: 'var(--gold)', boxShadow: '0 0 16px rgba(201,168,76,0.4)',
              margin: '0 auto 16px',
            }}
          />
          <div className="font-mono-dm" style={{ fontSize: '11px', letterSpacing: '0.18em', textTransform: 'uppercase' as const, color: 'var(--gold)', marginBottom: '12px' }}>
            Concierge
          </div>
          <p style={{ color: 'var(--text-muted)', fontSize: '14px', lineHeight: 1.6, margin: '0 0 20px' }}>
            No synthesis decision yet. Broadcast a prompt and let the council respond — the concierge
            will appear automatically after synthesis completes.
          </p>
          <button
            onClick={handleClose}
            className="reveal-pill"
            style={{ height: '36px', fontSize: '12px' }}
          >
            <X size={14} /> Close
          </button>
        </div>
      </div>
    );
  }

  const { alignment_summary, tension_points, recommended_direction, phase, model_used } = decision;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center"
      style={{ background: 'rgba(8,8,6,0.75)', backdropFilter: 'blur(8px)' }}
      onClick={handleClose}
    >
      <div
        onClick={e => e.stopPropagation()}
        style={{
          width: '100%',
          maxWidth: '620px',
          margin: '0 24px',
          borderRadius: '24px',
          border: '1px solid rgba(201,168,76,0.18)',
          background: 'linear-gradient(180deg, rgba(18,17,14,0.98), rgba(12,11,9,0.98))',
          boxShadow: '0 0 80px rgba(201,168,76,0.08), 0 24px 48px rgba(0,0,0,0.4)',
          overflow: 'hidden',
        }}
      >
        {/* Header */}
        <div
          className="flex items-center justify-between"
          style={{
            padding: '20px 28px',
            borderBottom: '1px solid rgba(255,255,255,0.045)',
          }}
        >
          <div className="flex items-center gap-3">
            <div
              style={{
                width: '8px',
                height: '8px',
                borderRadius: '50%',
                background: 'var(--gold)',
                boxShadow: '0 0 12px rgba(201,168,76,0.5)',
              }}
            />
            <span
              className="font-mono-dm"
              style={{
                fontSize: '11px',
                letterSpacing: '0.2em',
                textTransform: 'uppercase' as const,
                color: 'var(--gold)',
              }}
            >
              Concierge
            </span>
            {phase && (
              <span
                className="font-mono-dm"
                style={{
                  fontSize: '9px',
                  letterSpacing: '0.12em',
                  color: 'var(--text-dim)',
                  padding: '2px 8px',
                  borderRadius: '6px',
                  background: 'rgba(255,255,255,0.04)',
                  border: '1px solid rgba(255,255,255,0.06)',
                }}
              >
                {phase.replace(/_/g, ' ')}
              </span>
            )}
          </div>
          <button
            className="keycap"
            style={{ width: '28px', height: '28px' }}
            onClick={handleClose}
            title="Close (Esc)"
          >
            <X size={12} />
          </button>
        </div>

        {/* Body */}
        <div style={{ padding: '28px', maxHeight: '60vh', overflowY: 'auto' }}>
          {/* Alignment summary */}
          {alignment_summary && (
            <section style={{ marginBottom: '28px' }}>
              <div
                className="font-mono-dm"
                style={{
                  fontSize: '9px',
                  letterSpacing: '0.18em',
                  textTransform: 'uppercase' as const,
                  color: 'var(--text-dim)',
                  marginBottom: '10px',
                }}
              >
                Where the council agrees
              </div>
              <p
                style={{
                  fontSize: '15px',
                  lineHeight: 1.7,
                  color: 'rgba(232,230,224,0.88)',
                  fontWeight: 300,
                  margin: 0,
                }}
              >
                {alignment_summary}
              </p>
            </section>
          )}

          {/* Tension points */}
          {tension_points.length > 0 && (
            <section style={{ marginBottom: '28px' }}>
              <div
                className="font-mono-dm"
                style={{
                  fontSize: '9px',
                  letterSpacing: '0.18em',
                  textTransform: 'uppercase' as const,
                  color: 'var(--text-dim)',
                  marginBottom: '10px',
                }}
              >
                Points of tension
              </div>
              <ul
                style={{
                  margin: 0,
                  padding: '0 0 0 18px',
                  listStyle: 'disc',
                }}
              >
                {tension_points.map((point, i) => (
                  <li
                    key={i}
                    style={{
                      fontSize: '14px',
                      lineHeight: 1.65,
                      color: 'rgba(232,230,224,0.78)',
                      fontWeight: 300,
                      marginBottom: '6px',
                    }}
                  >
                    {point}
                  </li>
                ))}
              </ul>
            </section>
          )}

          {/* Recommended direction */}
          {recommended_direction && (
            <section>
              <div
                className="font-mono-dm"
                style={{
                  fontSize: '9px',
                  letterSpacing: '0.18em',
                  textTransform: 'uppercase' as const,
                  color: 'var(--text-dim)',
                  marginBottom: '10px',
                }}
              >
                Recommended direction
              </div>
              <p
                style={{
                  fontSize: '15px',
                  lineHeight: 1.7,
                  color: 'rgba(232,230,224,0.88)',
                  fontWeight: 300,
                  margin: 0,
                }}
              >
                {recommended_direction}
              </p>
            </section>
          )}
        </div>

        {/* Action bar */}
        <div
          className="flex items-center justify-between"
          style={{
            padding: '16px 28px 24px',
            borderTop: '1px solid rgba(255,255,255,0.045)',
          }}
        >
          <div className="flex items-center gap-3">
            <button
              className="reveal-pill"
              style={{
                height: '38px',
                fontSize: '12px',
                padding: '0 20px',
                background: 'var(--gold)',
                color: 'var(--void)',
                borderColor: 'transparent',
                fontWeight: 500,
              }}
              onClick={handleProceed}
            >
              <ArrowRight size={14} />
              Proceed
            </button>
            <button
              className="reveal-pill"
              style={{ height: '38px', fontSize: '12px', padding: '0 16px' }}
              onClick={handleRound2}
            >
              <RotateCcw size={12} />
              Round 2
            </button>
            <button
              className="reveal-pill"
              style={{ height: '38px', fontSize: '12px', padding: '0 16px' }}
              onClick={handleOverride}
            >
              <Pencil size={12} />
              Override
            </button>
            <button
              className="reveal-pill"
              style={{ height: '38px', fontSize: '12px', padding: '0 16px' }}
              onClick={handleDownload}
              title="Download concierge report as markdown"
            >
              <Download size={12} />
              Report
            </button>
          </div>
          {model_used && (
            <span
              className="font-mono-dm"
              style={{
                fontSize: '9px',
                letterSpacing: '0.1em',
                color: 'var(--text-dim)',
              }}
            >
              via {model_used}
            </span>
          )}
        </div>
      </div>
    </div>
  );
}
