import { useEffect, useCallback } from 'react';
import { useMaestro } from '../../context/MaestroContext';
import { useOrchestration } from '../../hooks/useOrchestration';
import { supabase } from '../../lib/supabase';
import { X, ArrowRight, RotateCcw, Pencil, Download } from 'lucide-react';
import type { SessionPhase, DesignMode } from '../../types';

/**
 * ConciergePanel — centered overlay showing the concierge's synthesis decision.
 *
 * B1 additions: intent-aware rendering.
 * - simple_ask → shows just the answer + Close
 * - design/pre_build/build/analysis → full alignment/tension/direction + phase routing
 */

const DESIGN_MODE_LABELS: Record<DesignMode, string> = {
  lite: '1 designer',
  standard: '2 designers',
  exploration: '4 designers',
};

const NEXT_PHASE_LABELS: Record<string, string> = {
  design: 'Design Phase',
  pre_build: 'Pre-Build',
  build: 'Build',
  analysis: 'Another Round',
};

export default function ConciergePanel() {
  const { state, dispatch } = useMaestro();
  const { broadcast } = useOrchestration();
  const decision = state.conciergeDecision;

  const handleClose = useCallback(() => {
    dispatch({ type: 'SET_CONCIERGE_VISIBLE', payload: false });
  }, [dispatch]);

  const advancePhase = useCallback(async (phase: SessionPhase, toastMsg: string) => {
    handleClose();
    if (state.activeSession) {
      await supabase
        .from('sessions')
        .update({ current_phase: phase } as never)
        .eq('id', state.activeSession.id);
      dispatch({ type: 'UPDATE_ACTIVE_SESSION', payload: { current_phase: phase } });
    }
    dispatch({ type: 'SHOW_TOAST', payload: toastMsg });
  }, [handleClose, state.activeSession, dispatch]);

  const handleProceed = useCallback(async () => {
    if (!decision) { handleClose(); return; }

    const next = decision.recommended_next_phase;

    if (next === 'design') {
      const modeLabel = decision.design_mode
        ? DESIGN_MODE_LABELS[decision.design_mode]
        : null;
      const toast = modeLabel
        ? `Starting Design (${modeLabel})`
        : 'Moving to Design phase';
      await advancePhase('design', toast);
    } else if (next === 'pre_build') {
      await advancePhase('pre_build', 'Moving to Pre-Build');
    } else if (next === 'build') {
      await advancePhase('build', 'Starting Build');
    } else if (next === 'analysis') {
      handleClose();
      dispatch({ type: 'SHOW_TOAST', payload: 'Ready for next round' });
    } else {
      // Fallback — no recommended_next_phase, default to design
      await advancePhase('design', 'Moving to Design phase');
    }
  }, [decision, handleClose, advancePhase, dispatch]);

  const handleRound2 = useCallback(() => {
    handleClose();
    const latestRound = state.rounds.length > 0
      ? state.rounds[state.rounds.length - 1]
      : null;
    if (latestRound) {
      const activeAgentIds = state.agents.filter(a => a.is_active).map(a => a.id);
      broadcast(latestRound.prompt, activeAgentIds);
    }
  }, [handleClose, state.rounds, state.agents, broadcast]);

  const handleOverride = useCallback(() => {
    dispatch({ type: 'SET_CONCIERGE_DECISION', payload: null });
    handleClose();
  }, [dispatch, handleClose]);

  const handleDownload = useCallback(() => {
    if (!decision) return;
    const roundNum = state.rounds.length > 0
      ? state.rounds[state.rounds.length - 1].round_number
      : 1;
    const sessionName = state.activeSession?.title ?? 'session';
    const md = [
      `# Concierge Report — ${sessionName} Round ${roundNum}`,
      '',
      '## Where the Council Agrees',
      decision.alignment_summary || '_No alignment summary._',
      '',
      '## Points of Tension',
      ...(decision.tension_points.length > 0
        ? decision.tension_points.map(p => `- ${p}`)
        : ['_No tension points identified._']),
      '',
      '## Recommended Direction',
      decision.recommended_direction || '_No recommendation._',
      '',
      `---`,
      `_Generated by Maestro Concierge${decision.model_used ? ` via ${decision.model_used}` : ''}_`,
    ].join('\n');

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `concierge-report-r${roundNum}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }, [decision, state.rounds, state.activeSession]);

  // Dismiss on Escape
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') handleClose();
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [handleClose]);

  // Sprint C · F1 — "Ask the council anyway" handler for triage simple_ask
  const handleAskCouncilAnyway = useCallback(() => {
    const triagePrompt = state.triageResult?.prompt ?? null;
    dispatch({ type: 'SET_TRIAGE_RESULT', payload: null });
    dispatch({ type: 'SET_CONCIERGE_VISIBLE', payload: false });
    if (triagePrompt) {
      const activeAgentIds = state.agents.filter(a => a.is_active).map(a => a.id);
      broadcast(triagePrompt, activeAgentIds);
    }
  }, [state.triageResult, state.agents, dispatch, broadcast]);

  // ─── Sprint C · F1 — Triage simple_ask view ──────────────────────────────
  const triage = state.triageResult;
  if (triage && state.conciergeVisible) {
    return (
      <div
        className="fixed inset-0 z-50 flex items-center justify-center"
        style={{ background: 'rgba(8,8,6,0.75)', backdropFilter: 'blur(8px)' }}
        onClick={handleClose}
      >
        <div
          onClick={e => e.stopPropagation()}
          style={{
            width: '100%', maxWidth: '520px', margin: '0 24px',
            padding: '40px 32px', borderRadius: '24px',
            border: '1px solid rgba(201,168,76,0.12)',
            background: 'linear-gradient(180deg, rgba(18,17,14,0.98), rgba(12,11,9,0.98))',
            boxShadow: '0 0 80px rgba(201,168,76,0.06), 0 24px 48px rgba(0,0,0,0.4)',
          }}
        >
          {/* Header */}
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '20px' }}>
            <div>
              <div className="font-mono-dm" style={{ fontSize: '11px', letterSpacing: '0.18em', textTransform: 'uppercase' as const, color: 'var(--gold)', marginBottom: '4px' }}>
                Concierge — Quick Answer
              </div>
              <div style={{ fontSize: '12px', color: 'var(--text-muted)' }}>
                Confidence: {Math.round(triage.confidence * 100)}%
              </div>
            </div>
            <button onClick={handleClose} style={{ background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer' }}>
              <X size={16} />
            </button>
          </div>

          {/* Answer */}
          <div style={{
            background: 'rgba(201,168,76,0.04)',
            border: '1px solid rgba(201,168,76,0.08)',
            borderRadius: '12px',
            padding: '20px',
            marginBottom: '20px',
          }}>
            <p style={{ color: 'var(--text-primary)', fontSize: '14px', lineHeight: 1.7, margin: 0, whiteSpace: 'pre-wrap' }}>
              {triage.direct_answer || triage.reasoning}
            </p>
          </div>

          {/* Actions */}
          <div style={{ display: 'flex', gap: '10px', justifyContent: 'flex-end' }}>
            <button onClick={handleAskCouncilAnyway} className="reveal-pill" style={{ height: '36px', fontSize: '12px', opacity: 0.7 }}>
              <RotateCcw size={14} /> Ask the council anyway
            </button>
            <button onClick={handleClose} className="reveal-pill" style={{
              height: '36px', fontSize: '12px',
              background: 'rgba(201,168,76,0.12)',
              borderColor: 'rgba(201,168,76,0.25)',
            }}>
              Got it
            </button>
          </div>
        </div>
      </div>
    );
  }

  // ─── Empty state (no decision yet) ───────────────────────────────────────
  if (!decision) {
    return (
      <div
        className="fixed inset-0 z-50 flex items-center justify-center"
        style={{ background: 'rgba(8,8,6,0.75)', backdropFilter: 'blur(8px)' }}
        onClick={handleClose}
      >
        <div
          onClick={e => e.stopPropagation()}
          style={{
            width: '100%', maxWidth: '420px', margin: '0 24px',
            padding: '40px 32px', borderRadius: '24px',
            border: '1px solid rgba(201,168,76,0.12)',
            background: 'linear-gradient(180deg, rgba(18,17,14,0.98), rgba(12,11,9,0.98))',
            boxShadow: '0 0 80px rgba(201,168,76,0.06), 0 24px 48px rgba(0,0,0,0.4)',
            textAlign: 'center' as const,
          }}
        >
          <div style={{
            width: '10px', height: '10px', borderRadius: '50%',
            background: 'var(--gold)', boxShadow: '0 0 16px rgba(201,168,76,0.4)',
            margin: '0 auto 16px',
          }} />
          <div className="font-mono-dm" style={{ fontSize: '11px', letterSpacing: '0.18em', textTransform: 'uppercase' as const, color: 'var(--gold)', marginBottom: '12px' }}>
            Concierge
          </div>
          <p style={{ color: 'var(--text-muted)', fontSize: '14px', lineHeight: 1.6, margin: '0 0 20px' }}>
            No synthesis decision yet. Broadcast a prompt and let the council respond — the concierge
            will appear automatically after synthesis completes.
          </p>
          <button onClick={handleClose} className="reveal-pill" style={{ height: '36px', fontSize: '12px' }}>
            <X size={14} /> Close
          </button>
        </div>
      </div>
    );
  }

  const { alignment_summary, tension_points, recommended_direction, phase, model_used, intent, design_mode, recommended_next_phase } = decision;
  const isSimpleAsk = intent === 'simple_ask';

  // ─── Recommended phase pill label ────────────────────────────────────────
  const nextPhaseLabel = recommended_next_phase
    ? NEXT_PHASE_LABELS[recommended_next_phase] ?? recommended_next_phase
    : null;
  const designModeLabel = design_mode ? DESIGN_MODE_LABELS[design_mode] : null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center"
      style={{ background: 'rgba(8,8,6,0.75)', backdropFilter: 'blur(8px)' }}
      onClick={handleClose}
    >
      <div
        onClick={e => e.stopPropagation()}
        style={{
          width: '100%', maxWidth: '620px', margin: '0 24px',
          borderRadius: '24px',
          border: '1px solid rgba(201,168,76,0.18)',
          background: 'linear-gradient(180deg, rgba(18,17,14,0.98), rgba(12,11,9,0.98))',
          boxShadow: '0 0 80px rgba(201,168,76,0.08), 0 24px 48px rgba(0,0,0,0.4)',
          overflow: 'hidden',
        }}
      >
        {/* Header */}
        <div className="flex items-center justify-between" style={{ padding: '20px 28px', borderBottom: '1px solid rgba(255,255,255,0.045)' }}>
          <div className="flex flex-col gap-1">
            <div className="flex items-center gap-3">
              <div style={{
                width: '8px', height: '8px', borderRadius: '50%',
                background: 'var(--gold)', boxShadow: '0 0 12px rgba(201,168,76,0.5)',
              }} />
              <span className="font-mono-dm" style={{ fontSize: '11px', letterSpacing: '0.2em', textTransform: 'uppercase' as const, color: 'var(--gold)' }}>
                Concierge
              </span>
              {phase && (
                <span className="font-mono-dm" style={{
                  fontSize: '9px', letterSpacing: '0.12em',
                  color: 'var(--text-dim)', padding: '2px 8px',
                  borderRadius: '6px', background: 'rgba(255,255,255,0.04)',
                  border: '1px solid rgba(255,255,255,0.06)',
                }}>
                  {phase.replace(/_/g, ' ')}
                </span>
              )}
              {isSimpleAsk && (
                <span className="font-mono-dm" style={{
                  fontSize: '9px', letterSpacing: '0.12em',
                  color: '#5ab88e', padding: '2px 8px',
                  borderRadius: '6px', background: 'rgba(90,184,142,0.08)',
                  border: '1px solid rgba(90,184,142,0.15)',
                }}>
                  Quick answer
                </span>
              )}
            </div>
            {/* Recommended next phase — shown for non-simple-ask */}
            {!isSimpleAsk && nextPhaseLabel && (
              <div className="flex items-center gap-2" style={{ paddingLeft: '20px' }}>
                <span style={{ color: 'var(--text-dim)', fontSize: '11px' }}>→</span>
                <span className="font-mono-dm" style={{ fontSize: '10px', letterSpacing: '0.1em', color: 'rgba(201,168,76,0.65)' }}>
                  Recommended: {nextPhaseLabel}
                  {recommended_next_phase === 'design' && designModeLabel && ` (${designModeLabel})`}
                </span>
              </div>
            )}
          </div>
          <button className="keycap" style={{ width: '28px', height: '28px' }} onClick={handleClose} title="Close (Esc)">
            <X size={12} />
          </button>
        </div>

        {/* Body */}
        <div style={{ padding: '28px', maxHeight: '60vh', overflowY: 'auto' }}>
          {isSimpleAsk ? (
            /* Simple ask — just show the answer */
            <p style={{ fontSize: '15px', lineHeight: 1.7, color: 'rgba(232,230,224,0.9)', fontWeight: 300, margin: 0 }}>
              {recommended_direction || alignment_summary}
            </p>
          ) : (
            <>
              {alignment_summary && (
                <section style={{ marginBottom: '28px' }}>
                  <div className="font-mono-dm" style={{ fontSize: '9px', letterSpacing: '0.18em', textTransform: 'uppercase' as const, color: 'var(--text-dim)', marginBottom: '10px' }}>
                    Where the council agrees
                  </div>
                  <p style={{ fontSize: '15px', lineHeight: 1.7, color: 'rgba(232,230,224,0.88)', fontWeight: 300, margin: 0 }}>
                    {alignment_summary}
                  </p>
                </section>
              )}

              {tension_points.length > 0 && (
                <section style={{ marginBottom: '28px' }}>
                  <div className="font-mono-dm" style={{ fontSize: '9px', letterSpacing: '0.18em', textTransform: 'uppercase' as const, color: 'var(--text-dim)', marginBottom: '10px' }}>
                    Points of tension
                  </div>
                  <ul style={{ margin: 0, padding: '0 0 0 18px', listStyle: 'disc' }}>
                    {tension_points.map((point, i) => (
                      <li key={i} style={{ fontSize: '14px', lineHeight: 1.65, color: 'rgba(232,230,224,0.78)', fontWeight: 300, marginBottom: '6px' }}>
                        {point}
                      </li>
                    ))}
                  </ul>
                </section>
              )}

              {recommended_direction && (
                <section>
                  <div className="font-mono-dm" style={{ fontSize: '9px', letterSpacing: '0.18em', textTransform: 'uppercase' as const, color: 'var(--text-dim)', marginBottom: '10px' }}>
                    Recommended direction
                  </div>
                  <p style={{ fontSize: '15px', lineHeight: 1.7, color: 'rgba(232,230,224,0.88)', fontWeight: 300, margin: 0 }}>
                    {recommended_direction}
                  </p>
                </section>
              )}
            </>
          )}
        </div>

        {/* Action bar */}
        <div className="flex items-center justify-between" style={{ padding: '16px 28px 24px', borderTop: '1px solid rgba(255,255,255,0.045)' }}>
          {isSimpleAsk ? (
            /* Simple ask — only Close */
            <button className="reveal-pill" style={{ height: '38px', fontSize: '12px', padding: '0 20px' }} onClick={handleClose}>
              <X size={12} />
              Close
            </button>
          ) : (
            <div className="flex items-center gap-3">
              <button
                className="reveal-pill"
                style={{ height: '38px', fontSize: '12px', padding: '0 20px', background: 'var(--gold)', color: 'var(--void)', borderColor: 'transparent', fontWeight: 500 }}
                onClick={handleProceed}
              >
                <ArrowRight size={14} />
                {nextPhaseLabel ? `→ ${nextPhaseLabel}` : 'Proceed'}
              </button>
              <button className="reveal-pill" style={{ height: '38px', fontSize: '12px', padding: '0 16px' }} onClick={handleRound2}>
                <RotateCcw size={12} />
                Round 2
              </button>
              <button className="reveal-pill" style={{ height: '38px', fontSize: '12px', padding: '0 16px' }} onClick={handleOverride}>
                <Pencil size={12} />
                Override
              </button>
              <button className="reveal-pill" style={{ height: '38px', fontSize: '12px', padding: '0 16px' }} onClick={handleDownload} title="Download concierge report as markdown">
                <Download size={12} />
                Report
              </button>
            </div>
          )}
          {model_used && (
            <span className="font-mono-dm" style={{ fontSize: '9px', letterSpacing: '0.1em', color: 'var(--text-dim)' }}>
              via {model_used}
            </span>
          )}
        </div>
      </div>
    </div>
  );
}
