/* global React */

/* ═══════════════════════════════════════════════
   ORB — refined, smaller, supporting role
   Sizes: xs (12), sm (18), md (28), lg (48), xl (96)
   ═══════════════════════════════════════════════ */
function Orb({ size = 'md', state = 'idle', accent = 'var(--ember)' }) {
  const dim = { xs: 12, sm: 18, md: 28, lg: 48, xl: 96 }[size];
  const blur = { xs: 4, sm: 6, md: 10, lg: 18, xl: 36 }[size];
  return (
    <span className={`maestro-orb orb-${state}`} style={{
      display: 'inline-block',
      width: dim, height: dim,
      borderRadius: '50%',
      background: `radial-gradient(circle at 35% 30%, rgba(255,220,180,0.95) 0%, ${accent} 35%, rgba(80,40,20,0.4) 75%, transparent 100%)`,
      boxShadow: `0 0 ${blur}px ${blur/3}px ${accent}55, inset 0 0 ${blur/2}px rgba(255,220,180,0.3)`,
      flexShrink: 0,
    }} />
  );
}

/* Council voices — desaturated, distinctive */
const VOICES = [
  { id: 'claude',  name: 'Claude',  model: 'Sonnet 4.6',     color: 'var(--voice-claude)', initial: 'C', role: 'reasoner' },
  { id: 'gpt',     name: 'GPT',     model: '5.4 Builder',     color: 'var(--voice-gpt)',    initial: 'G', role: 'builder' },
  { id: 'gemini',  name: 'Gemini',  model: '2.5 Pro',         color: 'var(--voice-gemini)', initial: 'M', role: 'researcher' },
  { id: 'kimi',    name: 'Kimi',    model: 'K2',              color: 'var(--voice-kimi)',   initial: 'K', role: 'critic' },
];

/* ═══════════════════════════════════════════════
   SAMPLE COUNCIL ROUND — used by carousel readers
   ═══════════════════════════════════════════════ */
const SAMPLE_PROMPT = "Design a three-pane reader layout that handles 4k+ token agent responses without losing the user's place.";

const SAMPLE_RESPONSES = [
  {
    voice: VOICES[0],
    tldr: "Lead with a sticky table-of-contents. Lazy-render below the fold. Carousel siblings stay collapsed until summoned.",
    body: [
      { kind: 'p', text: "The core problem isn't length — it's orientation. When an agent dumps 4,000 tokens, the user needs to know where they are in the response and where they came from. I'd treat each response as a long-form document, not a chat bubble." },
      { kind: 'h', text: "Reader anatomy" },
      { kind: 'p', text: "Three rails: (1) a slim left rail showing section markers extracted from the response — H2s, code blocks, callouts. (2) the body itself, max-width 72ch, line-height generous. (3) the right rail holds the carousel — the other agents, collapsed to their tldr." },
      { kind: 'code', lang: 'tsx', text: "function CouncilReader({ round }) {\n  const [active, setActive] = useState(0);\n  const sections = useMemo(\n    () => extractSections(round.responses[active].body),\n    [round, active]\n  );\n  return (\n    <article>\n      <Rail sections={sections} />\n      <Body content={round.responses[active]} />\n      <Carousel\n        items={round.responses}\n        activeIndex={active}\n        onSelect={setActive}\n      />\n    </article>\n  );\n}" },
      { kind: 'h', text: "Navigation" },
      { kind: 'p', text: "←/→ moves between voices. ⌘↑/⌘↓ jumps between sections within a voice. The address bar reflects {round}/{voice}/{section} so deep-linking works." },
    ],
    confidence: 0.84,
    runtime: 12.4,
    tokens: 3840,
  },
  {
    voice: VOICES[1],
    tldr: "Don't overthink. Side-by-side cards with a focus mode. Cmd+1/2/3/4 jumps between voices.",
    body: [
      { kind: 'p', text: "I'd ship a card grid first — 4 cards visible, scaled down. Click any card or hit Cmd+N to expand it to focus mode. The other three slide off-screen but stay clickable as edge-tabs." },
      { kind: 'h', text: "Why this beats a carousel" },
      { kind: 'p', text: "Carousels hide content. The user has to remember 'oh right, Gemini said something about caching'. With a 4-up grid you can scan all four tldrs in one glance, then commit to reading one." },
      { kind: 'code', lang: 'tsx', text: "<Grid focused={focused}>\n  {responses.map((r, i) => (\n    <ResponseCard\n      key={r.voice.id}\n      response={r}\n      isFocused={focused === i}\n      onClick={() => setFocused(i)}\n      hotkey={i + 1}\n    />\n  ))}\n</Grid>" },
    ],
    confidence: 0.71,
    runtime: 8.1,
    tokens: 2120,
  },
  {
    voice: VOICES[2],
    tldr: "Synthesis-first. Show the merged answer up top; the four voices become annotations.",
    body: [
      { kind: 'p', text: "The user mostly wants the answer, not four answers. I'd lead with a synthesized response generated by Haiku, with inline citations [C][G][M][K] linking to the corresponding agent passage. Click a citation to drawer-open the source voice." },
      { kind: 'h', text: "Drawer mechanics" },
      { kind: 'p', text: "When the citation opens, the right 40% of the screen becomes a reader for that one voice, scroll-locked to the cited passage. The synthesis remains visible on the left so context is preserved." },
    ],
    confidence: 0.78,
    runtime: 14.2,
    tokens: 2960,
  },
  {
    voice: VOICES[3],
    tldr: "All three above are wrong. The unit is the disagreement, not the response. Show me where they conflict.",
    body: [
      { kind: 'p', text: "A council exists to surface tension. If you flatten that into 'four cards to read sequentially' you've thrown away the whole point. I'd build a tension map: extract claims from each voice, group claims that contradict, render the disagreements as a small UI of their own at the top." },
      { kind: 'h', text: "Conflict cards" },
      { kind: 'p', text: "Each conflict gets its own micro-component: 'Claude says X, GPT says ¬X. Tap to drill in.' The full responses live below the fold for archeology, but the conflict map is what the user actually scans." },
    ],
    confidence: 0.66,
    runtime: 11.0,
    tokens: 1840,
  },
];

/* Per-seat live state for the council (drives the advisor strip ring) */
const SAMPLE_SEAT_STATES = {
  claude: 'ready',     // body in
  gpt:    'streaming', // body partially in
  gemini: 'thinking',  // dots
  kimi:   'spoken',    // already read
};

const SAMPLE_THREADS = [
  { id: 't1', title: 'Tidewatch — refactor reader', kind: 'concierge', updated: '2m', active: true },
  { id: 't2', title: 'Carousel ergonomics', kind: 'broadcast', updated: '14m' },
  { id: 't3', title: 'Bouncer false-positives', kind: 'broadcast', updated: '1h' },
  { id: 't4', title: 'Sonnet 4.6 — direct', kind: 'direct', updated: '3h' },
  { id: 't5', title: 'Build run · auth-redo', kind: 'execution', updated: 'yesterday' },
];

Object.assign(window, { Orb, VOICES, SAMPLE_PROMPT, SAMPLE_RESPONSES, SAMPLE_THREADS, SAMPLE_SEAT_STATES });
