/*
  # Add Agent Skills, Artifacts, and Scoped Paths

  ## Summary
  Extends the Maestro schema to support agent specialization via skills,
  downloadable file artifacts from agent responses, and scoped repository
  paths per agent.

  ## Changes

  ### Modified Tables
  - `responses`
    - Added `artifacts` (jsonb) - Array of file artifacts (filename, content_type, content) generated by agents
  - `agents`
    - Added `scoped_paths` (jsonb) - Array of file path globs this agent is scoped to in the connected repo

  ### New Tables
  - `agent_skills`
    - `id` (uuid, primary key)
    - `agent_id` (uuid, FK to agents)
    - `user_id` (uuid, FK to auth.users)
    - `name` (text) - Display name of the skill (e.g. "Code Generation", "UX Wireframing")
    - `instruction` (text) - System prompt fragment injected when the agent runs
    - `scoped_paths` (jsonb) - File path globs this skill applies to
    - `is_active` (boolean) - Whether this skill is currently enabled
    - `created_at` (timestamptz)

  ## Security
  - RLS enabled on `agent_skills`
  - All policies use auth.uid() to enforce user ownership
  - Separate SELECT, INSERT, UPDATE, DELETE policies
*/

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'responses' AND column_name = 'artifacts'
  ) THEN
    ALTER TABLE responses ADD COLUMN artifacts jsonb DEFAULT '[]';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'agents' AND column_name = 'scoped_paths'
  ) THEN
    ALTER TABLE agents ADD COLUMN scoped_paths jsonb DEFAULT '[]';
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS agent_skills (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_id uuid NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL DEFAULT '',
  instruction text NOT NULL DEFAULT '',
  scoped_paths jsonb DEFAULT '[]',
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE agent_skills ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can select own agent skills"
  ON agent_skills FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own agent skills"
  ON agent_skills FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own agent skills"
  ON agent_skills FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own agent skills"
  ON agent_skills FOR DELETE TO authenticated
  USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS agent_skills_agent_id_idx ON agent_skills(agent_id);
CREATE INDEX IF NOT EXISTS agent_skills_user_id_idx ON agent_skills(user_id);
